"""Validate the raw Parquet landing zone against the LATAM Bank data dictionary.

Checks, per table:
- Row count recounted from the Parquet files (footer metadata) and compared to the manifest
  written by ``fetch_to_parquet.py`` and to the row count stated in the data dictionary.
- Daily partition coverage for fact tables against the documented range 2023-06-17..2026-06-17.
- Primary-key duplicates (first column of each table, which is its PK per the dictionary).

Outputs ``documentation/reports/landing_validation.{md,json}``. Read-only on the data.

Usage:
    python scripts/data/validate_landing.py --dest data/raw_parquet --out documentation/reports
"""

from __future__ import annotations

import argparse
import json
import re
from datetime import date, timedelta
from pathlib import Path

import duckdb

# Row counts as stated in the organizer's data dictionary (see CORA_CONTEXT.md, "The 13 tables").
DICTIONARY_ROWS = {
    "customers": 150_000,
    "products": 400_000,
    "branches": 350,
    "service_agents": 1_200,
    "marketing_campaigns": 200,
    "daily_exchange_rates": 3_000,
    "transactions": 5_000_000,
    "call_center_interactions": 800_000,
    "call_transcripts": 200_000,
    "satisfaction_surveys": 250_000,
    "digital_events": 10_000_000,
    "complaints": 80_000,
    "campaign_sends": 2_000_000,
}
RANGE_START, RANGE_END = date(2023, 6, 17), date(2026, 6, 17)
# Composite primary keys per the dictionary; every other table uses its first column.
COMPOSITE_PK = {"daily_exchange_rates": ["date", "source_currency", "target_currency"]}
DAY_RE = re.compile(r"year=(\d{4})/month=(\d{2})/day=(\d{2})")


def glob_for(dest: Path, table: str) -> str:
    single = dest / f"{table}.parquet"
    path = single if single.exists() else dest / table / "**" / "*.parquet"
    return str(path).replace("\\", "/")


def validate(con: duckdb.DuckDBPyConnection, dest: Path, table: str) -> dict:
    pattern = glob_for(dest, table)
    files = con.execute(
        f"SELECT file_name, sum(row_group_num_rows) FROM (SELECT DISTINCT file_name, row_group_id, "
        f"row_group_num_rows FROM parquet_metadata('{pattern}')) GROUP BY file_name"
    ).fetchall()
    rows = int(sum(n for _, n in files))
    manifest = json.loads((dest / "_manifests" / f"{table}.json").read_text(encoding="utf-8"))
    first_col = con.execute(f"DESCRIBE SELECT * FROM read_parquet('{pattern}')").fetchone()[0]
    pk_cols = COMPOSITE_PK.get(table, [first_col])
    pk = ", ".join(pk_cols)
    quoted = [f'"{c}"' for c in pk_cols]
    key = ", ".join(quoted)
    all_set = " AND ".join(f"{c} IS NOT NULL" for c in quoted)
    any_null = " OR ".join(f"{c} IS NULL" for c in quoted)
    distinct_pk = con.execute(
        f"SELECT count(*) FROM (SELECT DISTINCT {key} FROM read_parquet('{pattern}') WHERE {all_set})"
    ).fetchone()[0]
    null_pk = con.execute(f"SELECT count(*) FROM read_parquet('{pattern}') WHERE {any_null}").fetchone()[0]

    expected = DICTIONARY_ROWS[table]
    result = {
        "table": table,
        "rows_parquet": rows,
        "rows_manifest": manifest["rows"],
        "manifest_matches": rows == manifest["rows"],
        "manifest_failures": len(manifest["failures"]),
        "rows_dictionary": expected,
        "delta_vs_dictionary_pct": round(100 * (rows - expected) / expected, 1),
        "files": len(files),
        "pk_column": pk,
        "pk_distinct": distinct_pk,
        "pk_nulls": null_pk,
        # Rows that repeat an already-seen non-null PK value.
        "pk_duplicate_rows": rows - null_pk - distinct_pk,
    }
    days = sorted(
        {date(*map(int, m.groups())) for f, _ in files if (m := DAY_RE.search(f.replace("\\", "/")))}
    )
    if days:
        expected_days = {RANGE_START + timedelta(d) for d in range((RANGE_END - RANGE_START).days + 1)}
        missing = sorted(expected_days - set(days))
        result.update(
            {
                "first_day": days[0].isoformat(),
                "last_day": days[-1].isoformat(),
                "days_present": len(days),
                "days_expected": len(expected_days),
                "days_missing": len(missing),
                "missing_days": [d.isoformat() for d in missing],
                "days_outside_range": [d.isoformat() for d in days if d not in expected_days],
            }
        )
    return result


def to_markdown(results: list[dict]) -> str:
    total = sum(r["rows_parquet"] for r in results)
    lines = [
        "# Raw landing validation",
        "",
        "Generated by `scripts/data/validate_landing.py` over `data/raw_parquet/`",
        "(all 13 tables, full history).",
        "Row counts are recounted from Parquet footers and compared to the ingestion manifests and to the",
        "row counts stated in the organizer's data dictionary. The PK is the first column of each table",
        "(composite `date, source_currency, target_currency` for `daily_exchange_rates`).",
        "",
        f"**Total rows landed:** {total:,} (dictionary: ~19,000,000).",
        "",
        "| Table | Rows (Parquet) | = Manifest | Dictionary | Δ vs dictionary | PK "
        "| PK duplicates | PK nulls | Days present / expected |",
        "|---|---:|:---:|---:|---:|---|---:|---:|---:|",
    ]
    for r in results:
        days = f"{r['days_present']} / {r['days_expected']}" if "days_present" in r else "n/a (snapshot)"
        lines.append(
            f"| `{r['table']}` | {r['rows_parquet']:,} | {'yes' if r['manifest_matches'] else '**NO**'} | "
            f"{r['rows_dictionary']:,} | {r['delta_vs_dictionary_pct']:+.1f}% | `{r['pk_column']}` | "
            f"{r['pk_duplicate_rows']:,} | {r['pk_nulls']:,} | {days} |"
        )
    gaps = [r for r in results if r.get("days_missing")]
    if gaps:
        lines += ["", "## Missing daily partitions", ""]
        for r in gaps:
            lines.append(
                f"- `{r['table']}`: {r['days_missing']} days missing: {', '.join(r['missing_days'])}"
            )
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dest", type=Path, default=Path("data/raw_parquet"))
    ap.add_argument("--out", type=Path, default=Path("documentation/reports"))
    args = ap.parse_args()
    con = duckdb.connect()
    con.execute("SET memory_limit='2GB'; SET threads=4")
    results = [validate(con, args.dest, t) for t in DICTIONARY_ROWS]
    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "landing_validation.json").write_text(json.dumps(results, indent=1), encoding="utf-8")
    (args.out / "landing_validation.md").write_text(to_markdown(results), encoding="utf-8")
    print(to_markdown(results))
    return 0 if all(r["manifest_matches"] and not r["manifest_failures"] for r in results) else 1


if __name__ == "__main__":
    raise SystemExit(main())
