"""Run-report builder: JSON + markdown for the quality checks (task 1.3, REQ-21/REQ-22).

`build_report` runs `run_checks` per table and aggregates the results into a `QualityReport`,
labeling each metric full or sampled. `report_to_json` / `report_to_markdown` emit the two
artifacts; the markdown mirrors `scripts/data/validate_landing.py`'s structure (title,
provenance line, "reproduce" line, one row per table, footnotes) and compares measured rates
against the DOCUMENTED expectations (~2% dup, ~5% null) while honestly reporting observed
PK-dup / orphan-FK ~0% and high structural nulls in specific columns.
"""

from __future__ import annotations

import duckdb

from cora.data.datasource import FACTS, DataSource

from .checks import run_checks
from .types import CheckResult, QualityReport

# Default partition used to bound a fact scan when sampling (present in the landing).
DEFAULT_SAMPLE_YEAR = 2026
DEFAULT_SAMPLE_MONTH = 6


class _SampledFactSource(DataSource):
    """Serves a bounded fact sample from an in-memory relation; delegates parents.

    The bounded fact rows are fetched once via the real `source.fetch_df(...)` (which caps
    the read) and registered as a DuckDB view on a fresh connection, so the many per-check
    aggregate queries hit a tiny in-memory relation instead of re-scanning the partition
    files each time. FK-parent dimensions are read directly from the real source's Parquet
    (small, read whole) using the same connection via its `read_parquet(...)` expression.
    """

    def __init__(self, source: DataSource, fact: str, year: int, month: int, limit: int) -> None:
        self._real = source
        self._fact = fact
        self._con = duckdb.connect()
        sample = source.fetch_df(fact, year=year, month=month, limit=limit)
        self._con.register(f"sample_{fact}", sample)

    def _source(self, table: str) -> str:
        if table == self._fact:
            return f"sample_{self._fact}"
        return self._real._source(table)  # FK parent dimension, read in place

    def _connect(self) -> duckdb.DuckDBPyConnection:
        return self._con


def build_report(
    source: DataSource,
    tables: list[str],
    *,
    sample_limit: int | None = None,
    year: int | None = None,
    month: int | None = None,
) -> QualityReport:
    """Run all checks over `tables`. When `sample_limit` is set, facts are bounded to one
    partition (`year`/`month`, defaulting to the present 2026-06) and labeled sampled.
    """
    y = year if year is not None else DEFAULT_SAMPLE_YEAR
    m = month if month is not None else DEFAULT_SAMPLE_MONTH
    results: list[CheckResult] = []
    for table in tables:
        if sample_limit is not None and table in FACTS:
            sampled = _SampledFactSource(source, table, y, m, sample_limit)
            results += run_checks(sampled, table, sample_limit=sample_limit)
        else:
            results += run_checks(source, table)
    scope = "sampled" if sample_limit is not None else "full"
    return QualityReport(results=results, tables=list(tables), scope=scope, sample_size=sample_limit)


def report_to_json(report: QualityReport) -> dict[str, object]:
    """Machine-readable metrics.json-style dict."""
    return report.to_dict()


def _pct(result: CheckResult) -> str:
    return f"{100 * result.rate:.2f}%"


def _max_null(results: list[CheckResult]) -> str:
    nulls = [r for r in results if r.check == "null_rate" and r.denominator]
    if not nulls:
        return "n/a"
    worst = max(nulls, key=lambda r: r.rate)
    return f"`{worst.column}` {100 * worst.rate:.1f}%"


def _violation_count(results: list[CheckResult], check: str) -> int:
    return sum(r.numerator for r in results if r.check == check)


def report_to_markdown(report: QualityReport) -> str:
    """Per-table markdown report comparing measured rates to documented expectations."""
    scope_note = (
        f"sampled (fact tables bounded to one partition, limit {report.sample_size})"
        if report.scope == "sampled"
        else "full history"
    )
    lines = [
        "# Data quality report",
        "",
        "Generated by `scripts/data/quality_report.py` over `data/raw_parquet/` via the",
        "`DataSource` abstraction. Checks are DuckDB aggregate SQL; dimensions are read whole",
        "and fact tables only via a bounded sample (never materialized in full). Numbers carry",
        f"numerators and denominators in the JSON sibling `data_quality.json`. Scope: {scope_note}.",
        "",
        "Reproduce: `uv run python scripts/data/quality_report.py`",
        "",
        "Documented expectations (organizer dictionary): ~2% duplicates, ~5% nulls, small",
        "orphan-FK rate. Observed (EDA F4/F5/F6, §10.5): PK-dup and orphan-FK ~0% full",
        "history; nulls are NOT uniform ~5% but structural and concentrated in specific",
        "columns (e.g. `credit_limit`/`days_past_due` ~69%, `complaints.origin_interaction_id`",
        "100%). This report states the measured rates honestly against those expectations.",
        "",
        "| Table | PK-dup | Row-hash-dup | Max null column | Orphan-FK | Enum viol. "
        "| Out-of-range | Currency viol. |",
        "|---|---:|---:|---|---:|---:|---:|---:|",
    ]
    for table in report.tables:
        rows = report.for_table(table)
        pk = next((r for r in rows if r.check == "pk_duplicate"), None)
        rh = next((r for r in rows if r.check == "row_hash_duplicate"), None)
        orphans = [r for r in rows if r.check == "orphan_fk"]
        orphan_txt = max((_pct(r) for r in orphans), default="n/a") if orphans else "n/a"
        lines.append(
            f"| `{table}` | {_pct(pk) if pk else 'n/a'} | {_pct(rh) if rh else 'n/a'} | "
            f"{_max_null(rows)} | {orphan_txt} | {_violation_count(rows, 'enum_violation')} | "
            f"{_violation_count(rows, 'out_of_range')} | {_violation_count(rows, 'currency')} |"
        )

    # Non-nullable columns that actually carry nulls (true violations), per table.
    lines += ["", "## Non-nullable columns with observed nulls", ""]
    any_viol = False
    for table in report.tables:
        bad = [
            r
            for r in report.for_table(table)
            if r.check == "null_rate" and r.numerator > 0 and (r.expected or "").startswith("non-nullable")
        ]
        if bad:
            any_viol = True
            cols = ", ".join(f"`{r.column}` ({r.numerator}/{r.denominator})" for r in bad)
            lines.append(f"- `{table}`: {cols}")
    if not any_viol:
        lines.append("- None: every non-nullable contract column is fully populated in scope.")

    lines += [
        "",
        "## Notes",
        "",
        "- Currency allow-sets (ADR-016/017): `products`/`transactions` exclude MXN (F3);",
        "  `complaints` and `daily_exchange_rates` include MXN.",
        "- `digital_events` is intentionally excluded from the orphan-FK seed set (24% null",
        "  `customer_id`, 15.6M rows); include it only as bounded aggregate SQL over non-null",
        "  values if needed later.",
        "- Range bounds are introspected from the Pandera contracts (`credit_score` 300-850,",
        "  `fraud_score` 0-100, non-negative counts/costs, `date`/`process_date` window).",
        "",
    ]
    return "\n".join(lines) + "\n"
